export const SEARCH = 'SEARCH';
export const SEARCH_BY_CEP_REQUESTED = 'SEARCH_BY_CEP_REQUESTED';
export const SEARCH_BY_CEP_FAILED = 'SEARCH_BY_CEP_FAILED';
export const SEARCH_BY_CEP_SUCCEEDED = 'SEARCH_BY_CEP_SUCCEEDED';
